#!/bin/sh
# [ -r env ] && {
# 	unset $(env | awk -F= '/^\w/ {print $1}' | xargs)
# 	. env
# }
# for file in *; do [ -h "$file" ] && rm "$file"; done
# for dir in runsvdir/*; do ln -s "$dir" .; done
# exec runsvdir runsvdir

# {

. ./conf
for serv in $services; do
	sv x "../$serv"
	runsv "../$serv" &
	until sv u "../$serv"; do sleep 0.1; done
done

# wait for Xorg to die
trap 'exit' INT TERM
trap 'pkill -P $$' EXIT
while true; do
	pidwait -x Xorg &
	wait $! # so trap can take effect
	sleep 1
	pidof Xorg >/dev/null 2>&1 && continue # in case pidwait..crashes or somehting
	break
done
# now turn off these services
sv d .

# } > ~/log 2>&1
