#!/bin/sh

# sudo not required for some system commands
for command in sv pacman shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command
alias sudo='sudo '

se() {
	pwd="$(pwd)"
	cd ~/.local/bin
	file=${1-$(fzf)} &&
		$EDITOR "$file"
	cd "$pwd"
}

sandsh(){ # stop rogue NPM packages from deleting ~ or something
	[ $# -gt 0 ] && {
		cd "$1" || exit 1
		shift
	}
	bwrap.sh -interactive -exec --dev-bind 'printf %s\\0 /' \
	-exec --ro-bind-try 'printf %s\\0 /home /etc /usr /run /tmp/.X11-unix' \
	--bind "$PWD" "$PWD" --unshare-uts --hostname SANDBOX "$SHELL" "$@"
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	ffprobe="ffprobe -hide_banner" \
	winetricks="winetricks -q" \
	xiv="nsxiv"

# Colorize commands when possible.
alias \
	ls="ls --color=auto" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
	e='$EDITOR' \
	P="pacman" \
	p="nice paru" \
	z="zathura"

#special aliases
	command -v rlwrap >/dev/null && alias dash="rlwrap dash"

	alias \
	lf='lfpp' \
	dt='dt -g $HOME/build/repo/dotfiles'
