#!/bin/sh

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command
alias sudo='sudo '

se() {
	pwd="$(pwd)"
	cd ~/.local/bin
	file=${1-$(fzf)} &&
		$EDITOR "$file"
	cd "$pwd"
}

sandsh(){ # stop rogue NPM packages from deleting ~ or something
	[ $# -gt 0 ] && {
		cd "$1" || exit 1
		shift
	}
	bwrap.sh -preset game -interactive -exec --ro-bind 'echo "$HOME"' -exec --bind 'printf "%s\n" "$PWD" ~/.cache /tmp ~/.local/share/nvim ~/.local/state/nvim' \
		--share-net --hostname SANDBOX --ro-bind /etc /etc "$SHELL" "$@"
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	ffprobe="ffprobe -hide_banner" \
	winetricks="winetricks -q" \
	xiv="nsxiv"

# Colorize commands when possible.
alias \
	ls="ls --color=auto" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="shutdown -h now" \
	e='$EDITOR' \
	P="pacman" \
	p="paru" \
	z="zathura"

#special aliases
alias \
	which rlwrap >/dev/null && alias \
	dash="rlwrap dash"

	alias \
	lf='lfpp' \
	dt='dt -g $HOME/build/repo/dotfiles'
