slang=eng,english,en,enm,enUS
alang=jp,jpn,en,eng

# Start in fullscreen mode by default.
fs=no

# screnshot
screenshot-format=png

screenshot-png-compression=6

screenshot-tag-colorspace=yes

screenshot-high-bit-depth=yes

hwdec=no
#vo=gpu
#gpu-context=wayland

keepaspect=yes
save-position-on-quit

audio-device=pipewire/default
volume=100

sub-auto=fuzzy

osd-fractions

# don't stop displaying images after 5 second
image-display-duration=inf
# load the next image before viewing it
prefetch-playlist
# loop around playlists
loop-playlist=inf
# make playlists automatically
autocreate-playlist=filter
# don't move onto next video or quit on video end.
keep-open=always
# reset zoom, alignment and rotation between images
reset-on-next-file=video-zoom,panscan,video-unscaled,video-align-x,video-align-y,video-rotate

# Show this after loading a new file. You can show text permanently instead by setting osd-msg1.
# osd-playing-msg=${!playlist-count==1:[${playlist-pos-1}/${playlist-count}] }${media-title} ${?width:${width}x${height}} ${?current-tracks/video/image==no:${?percent-pos==0:${duration}}${!percent-pos==0:${time-pos} / ${duration} (${percent-pos}%)}}
# osd-playing-msg-duration=7000

# On most platforms you can make the background transparent and avoid black
# bars while still having all the screen space available for zooming in:
background=none
background-color=0/0

# Set options for stand-alone images (not cover art).
# The condition is written not to restore and reapply the options on each image
# because that is inefficient, especially for toggling --d3d11-flip which
# reinits the VO.
[image]
profile-cond=(get('current-tracks/video/image') and not get('current-tracks/video/albumart')) or (not get('current-tracks/video') and get('user-data/mpv/image'))
profile-restore=copy
# enable the image-only bindings in input.conf. Use allow-hide-cursor+allow-vo-dragging to preserve window dragging.
input-commands-append=no-osd set user-data/mpv/image 1; enable-section image allow-hide-cursor
# Either use the slimbottombar OSC layout optimized for images...
# script-opt=osc-layout=slimbottombar
# script-opt=osc-deadzonesize=0.9
# ...or disable it altogether
osc=no
video-recenter # recenter after zooming out
# don't show a full green progress in Windows' taskbar
taskbar-progress=no

[non-image]
profile-cond=get('user-data/mpv/image') and (not get('current-tracks/video/image') or get('current-tracks/audio'))
# disable image key bindings
input-commands=no-osd del user-data/mpv/image; disable-section image

# # Loop short videos like gifs.
[loop-short]
profile-cond=duration < 60 and p['current-tracks/video/image'] == false and p['current-tracks/audio'] == nil
profile-restore=copy
loop-file

# Enable the screensaver when images are kept open forever.
[screensaver]
profile-cond=p['current-tracks/video'].image and not p['current-tracks/video'].albumart and image_display_duration == math.huge
profile-restore=copy
stop-screensaver=no
