#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config single_monocle false
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config gapless_monocle true
# bspc config initial_polarity first_child
bspc config initial_polarity second_child
bspc config automatic_scheme longest_side
# bspc config pointer_follows_focus true
bspc config pointer_motion_interval 60 # workarounds bullshit with window resizing
bspc config ignore_ewmh_focus true

bspc config focused_border_color "#FF00FF"
# bspc config active_border_color ""
# bspc config normal_border_color ""
# bspc config presel_feedback_color ""

bspc rule -a qbittorrent follow=on
bspc rule -a mpv state=pseudo_tiled
bspc rule -a Screenkey manage=off


sxhkd -c "$HOME/.config/sxhkd/sxhkdrcpp" &
servtoggle.sh -q polybar
notify-send Loaded
